#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

printf "\n\n 🚀 Running prettier on staged changes 🚀 \n\n"

prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
git update-index --again

printf "\n\n 🚀 Running build command 🚀 \n\n"

pnpm run build 

