#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


printf "\n 🚀 Running prettier on staged changes 🚀 \n" 

prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
git update-index --again

printf "\n 🚀 Running build command 🚀 \n" 

pnpm run build 

